### ISSUE TITLE
Code handling

### ISSUE THREAD

**Issue by richardvokral** [casualwriter/vanilla-chatgpt#3]
Hello thanks for great code. I have issue whet inputing code and code related questions as the code will messup the page. Example: i input the code od vanilla-chatgpt and ask what this code does, then in reply it will copy the whole frontend...

**Comment by casualwriter** [comment]
can u provide some sample?

**Comment by richardvokral** [comment]
Hello, I just copy the code of vanilla-chatgpt to the prompt and it behaves as in the screenshot.
using chrome 114.0.5735.199

![Výstřižek](https://github.com/casualwriter/vanilla-chatgpt/assets/139554953/f848fdc9-5935-40e6-af65-8aadd4e8fa8a)

**Comment by casualwriter** [comment]
I see. should be somewhere html code mess up the screen. please quote the code in code-block ```{code}``` or ~~~{code}~~~ in the prompt. if still have problem, use <xmp>{code}</xmp> to disable the effect of html code.
